### ISSUE TITLE
JSON parse error?

### ISSUE THREAD

**Issue by navigator117** [dvidelabs/flatcc#50]
It seems if the keyword in schema file is too long, It will be truncate in JSON parser and the result is the keyword can't be matched.  
for example:
aaaa_bbbb_steps,
aaaa_bbbb_start_steps,
then the second one will be truncate to aaaa_bbbb_start, and result fail to match symbol.

**Comment by mikkelfj** [comment]
The following schema reproduce the problem:

```
enum issue50 : ubyte {
    aaaa_bbbb_steps,
    aaaa_bbbb_start_steps
}
```

As far as I can tell, the parser attempts to match `aaaa_bbbb_start_` which is exactly two 8 byte groups. The parser fails to realize that it might need to load more data to confirm the match.

```
static const char *issue50_parse_json_enum(flatcc_json_parser_t *ctx, const char *buf, const char *end,
        int *value_sign, uint64_t *value, int *aggregate)
{
    const char *unmatched = buf;
    const char *mark;
    uint64_t w;

    w = flatcc_json_parser_symbol_part(buf, end);
    if (w == 0x616161615f626262) { /* prefix "aaaa_bbb" */
        buf += 8;
        w = flatcc_json_parser_symbol_part(buf, end);
        if ((w & 0xffffffffffffff00) == 0x625f737465707300) { /* "b_steps" */
            buf = flatcc_json_parser_match_constant(ctx, (mark = buf), end, 7, aggregate);
            if (buf != mark) {
                *value = UINT64_C(0), *value_sign = 0;
            } else {
                return unmatched;
            }
        } else { /* "b_steps" */
            if (w == 0x625f73746172745f) { /* "b_start_" */
                buf = flatcc_json_parser_match_constant(ctx, (mark = buf), end, 8, aggregate);
                if (buf != mark) {
                    *value = UINT64_C(1), *value_sign = 0;
                } else {
                    return unmatched;
                }
            } else { /* "b_start_" */
                return unmatched;
            } /* "b_start_" */
        } /* "b_steps" */
    } else { /* prefix "aaaa_bbb" */
        return unmatched;
    } /* prefix "aaaa_bbb" */
    return buf;
}
```

**Comment by mikkelfj** [comment]
This is an optimization gone wrong, quote comment:

``` * While not the original intention, the `gen_prefix_trie` also handles the
 * special case where the set has two keys where one is not a prefix of
 * the other, but both terminate in the same tag. In this case we can
 * immediately do an exact match test and skip the less than
 * comparision. We need no special code for this, assuming the function
 * is called correctly. This significantly reduces the branching in a
 * case like "Red, Green, Blue".
```

The assumption is that two keywords being tested by this function must end in the same 8-character block, but it appears the function is called without this being true. Commenting out the shorter enum name causes the full name to be checked as expected.

**Comment by mikkelfj** [comment]
I have  pushed a fix, but only inspected generated code - @navigator117 can you please confirm if this resolves the issue.

It only happens because there are exactly two keys with the same prefix, but the longer key ends in a different group of 8 characters lengthwise. Thus I would not expect most json parsers to be sensitive to this.

**Comment by mikkelfj** [comment]
I have an unpublished test case that confirms the fix, but it has uncovered a related problem that isn't fixed.

**Comment by mikkelfj** [comment]
The new issue is as follows:

Given three table field names (taken from monster_test.fbs, adding two new fields):

>  testjsonprefixparsing: ...
>  testjsonprefixparsing2: ...
>  testjsonprefixparsing3: ....

The parser builds a decision tree roughly relying on `testjsonprefixparsing` < `testjsonprefixparsing3` or more precisely the subword `rsing` < `rsing3`. But there is trailing data when testing an 8 byte word at a time so  e.g. `rsing:\x20\x20` > `rsing3\x00\x00`. The parser should therefore test the shorter prefix first, and it generally does, but apparently misses some edge cases. Renaming using _2 and _3 fixes the problem for table fields, but not for unquoted enums because other trailing characters are valid here affecting sort order.

A fix is being worked on.

**Comment by mikkelfj** [comment]
The test cases are now added to https://github.com/dvidelabs/flatcc/commit/3a151f54ca174336ae5388ca8b1a5c886df7268a

**Comment by mikkelfj** [comment]
Should be fixed now.

This uncovered a major mishandling of prefixes that required reworking the entire trie generator. The trie generator has a special sub-generator for prefixes but if this prefix trie fails to match it cannot assume that the match has failed - it must proceed to test other keys that are not prefixes - if any such exists. The code generator had no reasonable way to deal with this - so needed a rewrite. Good thing is that all tests, including new ones, passed in first attempt after the rewrite.

https://github.com/dvidelabs/flatcc/commit/cbe4f1b4c239a16919471f7077fed782b1290817

Keeping issue open to get confirmation by @navigator117

**Comment by navigator117** [comment]
After pull the latest code and test, It is still not fixed. And I found another, if I defined schema as:
union FileAny
{
    FileGameConf,
}

table FileGameConf
{
...
}

table File                                                                
{
    any:FileAny;                                                                
}
root_type File;
and the JSON file as:
{
    "any_type": "FileGameConf",
    "any": {
...
}
}
the json parser will report "expected literal or symbolic scalar!" at FileGameConf keyword. But if I replace FileGameConf with FileConf, It will be OK.
May be help.

**Comment by mikkelfj** [comment]
Thanks for the update - I will look into it.

**Comment by mikkelfj** [comment]
@navigator117  or others, please let me know if this is a show stopper. I'm working on some related parser features so it is not convenient to dig into this issue any further before that other work matures, unless it it is important.

**Comment by mikkelfj** [comment]
@navigator117 
I have added a temporary branch "flatcc-issue50" with test/issue50/build.sh

I have not been able to reproduce the last problem you mentioned.

The original problem could be reproduced but was fixed, and I added test cases in test/json_test/test_json.c and in test/monster_test/monster_test.fbs to cover that.
Some of those are found in this commit: https://github.com/dvidelabs/flatcc/commit/cbe4f1b4c239a16919471f7077fed782b1290817

Could you please have another look?
You could add a pull request on the flatcc-issue50 branch - it will not be merged - its just for testing.

I did suspect there might be another issue related to json_parser.c functions that decide when a name is valid. If you can provide me with an executable test case that fails, I suspect it would not be difficult to fix.

**Comment by mikkelfj** [comment]
I'm about to make a new release - only waiting for feedback on this.

**Comment by navigator117** [comment]
test with branch flatcc-issue50, and it's fixed!

**Comment by mikkelfj** [comment]
thanks!
